sudo: false

language: ruby
rvm:
  - 2.3.3

install:
  - gem install html-proofer
script:
  - bundle install --path vendor/bundle
  - bundle exec jekyll build
  - ln -sf . _site/vbuf
  - htmlproofer ./_site
  - rm _site/vbuf

branches:
  only:
  - master

cache:
  directories:
    - vendor/bundle

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_deploy:
  - rm -rf _posts docker vendor README.md .travis.yml .bundle .gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: jdrios@gmail.com
  name: travis-bot
  target_branch: gh-pages
  on:
    branch: master
