sudo: false

language: ruby
rvm:
  - 2.3.3

install:
  - gem install html-proofer
script:
  - bundle install --path vendor/bundle
  - jekyll build
  - htmlproofer ./_site

branches:
  only:
  - master

cache:
  directories:
    - vendor/bundle

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master
