# Site settings
title: VBUF
email: jdrios@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /vbuf
url: ""
twitter_username: jotadrilo
github_username:  jotadrilo

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
