FROM ruby:3.3

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    apt-get install -y --no-install-recommends nodejs && \
    rm -r /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /blog

ENV BUNDLE_PATH=/vendor/bundle
ENTRYPOINT ["bundle"]
