version: '2'

services:
  bundle:
    image: vbuf:latest
    entrypoint: bundle
    command: install
    volumes:
      - ../vendor:/vendor
  vbuf:
    image: vbuf:latest
    entrypoint: jekyll
    command: serve --host 0.0.0.0 --incremental
    ports:
      - 4000:4000
    volumes:
      - ..:/src
    volumes_from:
      - bundle:ro
