title: VBUF
author: jotadrilo
email: josriolop@gmail.com
description: >
  Vida bajo un flexo, es solo eso.

twitter_username: jotadrilo
github_username:  jotadrilo
instagram_username: jotadrilo

show_excerpts: false

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
